---
# tasks file for ansible-role-docker-ce

- name: Determine Docker version
  command: bash -c "docker version | grep Version | awk '{print $2}'"
  ignore_errors: yes
  changed_when: false
  register: cmd_docker_version

- name: Set fact if old Docker installation shall be removed
  set_fact:
    remove_old_docker: "{{docker_remove_pre_ce | bool }} == true and {{ cmd_docker_version.stdout_lines[0] | search('-ce') }} == false"
  when: cmd_docker_version.stdout_lines is defined and cmd_docker_version.stdout_lines[0] is defined

- name: Check if Docker is running
  command: systemctl status docker
  ignore_errors: yes
  changed_when: false
  register: service_docker_status
  when: remove_old_docker | default(false) | bool == true
  become: true

- name: Stop Docker service
  service:
    name: docker
    state: stopped
  when: "service_docker_status.rc | default(1) == 0"

- name: Remove old Docker installation before Docker CE
  package:
    name: "{{ item }}"
    state: absent
  become: true
  when: remove_old_docker|default(false) | bool == true
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Ensure docker-ce is the latest version
  package:
    name: docker-ce
    state: latest
  become: true
  notify: restart docker

- name: Ensure /etc/docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  become: true

- name: Configure Docker daemon (file)
  copy:
    src: "{{ docker_daemon_config_file }}"
    dest: /etc/docker/daemon.json
  become: true
  notify: restart docker
  when: docker_daemon_config_file is defined

- name: Configure Docker daemon (variables)
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
  become: true
  notify: restart docker
  when: docker_daemon_config_file is not defined and 
        docker_daemon_config is defined

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: true

